### ISSUE TITLE
[Broken] No output and Unhandled Exception: SystemArgumentOutOfRangeException: StartIndex cannot be less than zero. Parameter name: startIndex

### ISSUE THREAD

**Issue by vavavr00m** [poynty/ArkCodeGeneratorRedux#1]
This is my first time compiling anything. I have no idea what I'm actually doing but research led me to use msbuild and also install visual studio. With msbuild cmd line, I just downloaded the zip, extracted, ran cmd, cd into that folder and entered the build command. With Visual Studio, I cloned the git and built it from the sln. Both produced three files namely ArkCodeGeneratorRedux.exe, ArkCodeGeneratorRedux.pdb, and ArkCodeGeneratorRedux.exe.config. Moving the files manually to the mod\WindowsNoEdit folder and launching either exe from there did nothing as well as running from a batch script. No output.txt was generated & there was an [error](https://github.com/andreashagstrom/SpawnCodeGenerator/issues/3) but SpawnCodeGenerator from @andreashagstrom produces the output.txt with Engrams list albeit missing the Spawn Codes. The unhandled exception is similar to aforementioned linked issue. Output.txt and screenshot are also there. Running W10 x64, if it matters. If you need any other info, please don't hesitate to let me know. Any help will be much appreciated.

**Comment by poynty** [comment]
You only need the ArkCodeGeneratorRedux.exe, the other files are build artifacts associated with the DEBUG build setting used for debugging.

I just rebuilt and tested it. It seems to work on the mods I just tried it on. To be clear the exe should be put in the mod folder you would like spawn commands for, for example in "SteamLibrary\steamapps\common\ARK\ShooterGame\Content\Mods\2890224647".

I could post a pre-compiled version but then you have to trust I am not up to anything fishy unless you know your way around dot.peek or similar.

As an example I just ran the file in the mod directory for the Ark mod DOX (id:710880648), it generated the output which I have put on [pastebin](https://pastebin.com/6Gvd1gwN)

Mod authors typically put their mod ID on the Steam Workshop page for their mod. If not you can find it in the address bar on the mod page. So lets say your mod had the ID 111111111 then you would be looking for the folder "SteamLibrary\steamapps\common\ARK\ShooterGame\Content\Mods\111111111".

**Comment by vavavr00m** [comment]
@poynty Interesting. You're right. It works IF the executable is in that specific mod directory, however, mine is a fresh install (around March or April 2023) and the mod folder is now \SteamLibrary\steamapps\workshop\content\346110\. The only reason I see the old mod directory was because of a launcher I tried yesterday because the downloads were extremely slow but all legal downloads (using the official Steam client) go to the new one.

1. Can you please make it work with `\SteamLibrary\steamapps\workshop\content\346110\{mod id}` and/or with the mod subdirectory LinuxNoEditor & WindowsNoEditor? Here's my [dir list](https://github.com/poynty/ArkCodeGeneratorRedux/files/11703540/Ark.new.mod.directory.zip) generated with [Snap2HTML](https://github.com/rlv-dan/Snap2HTML)

2. Can you please remove the part of the output before PullResourceAdditions because it's a duplicate?

![image](https://github.com/poynty/ArkCodeGeneratorRedux/assets/4675132/b9121ff9-b842-4968-9707-765f130d3ab5)

![image](https://github.com/poynty/ArkCodeGeneratorRedux/assets/4675132/cfe824fb-ec46-496f-9a80-cad79c4e766a)

**Comment by andreashagstrom** [comment]
It'd be very unwise to have it working in the ARK root-folder(346110). The strain of generating one single text document for all mods. Remember that many people have like 100+ mods installed, even if they only use a fraction of them, old installs are there.

The program is made to grab the files from one folder(mod) at a time for a VERY good reason. With that said, this version's author might do what you ask for.

**Comment by vavavr00m** [comment]
@andreashagstrom I understand & can see where the confusion is coming from. The request is simply to be able to handle alternative directories (not to run the generator from Ark's mods root directory) since neither your fork nor @poynty's works properly with:

- `\SteamLibrary\steamapps\workshop\content\346110\{mod id}\`
- `\SteamLibrary\steamapps\workshop\content\346110\{mod id}\WindowsNoEditor\`
- `\SteamLibrary\steamapps\workshop\content\346110\{mod id}\LinuxNoEditor\`

I will edit my previous comment to make this clear.

**Comment by poynty** [comment]
I do not have this directory structure to debug it. When did this become a thing? Neither my local install or any of my dedicated servers have this folder structure.

The dual notices delineates the portion of output directly created by the original author and is there as a mark of respect so I would prefer to leave it, you are welcome to edit the code and comment out line 210 with a // in program.cs

Looking through your folder structure (thanks for that) it seems likely that the files are now provided in a compressed state with the extension uasset.z rather than uasset. I don't have any of them to test the compression method but it is likely just a zip.

Can you upload this mod from your folder in a zip: 1681125667 somewhere, I can grab it and i'll see if I can fix it for this folder/file structure.

**Comment by vavavr00m** [comment]
> I do not have this directory structure to debug it. When did this become a thing? Neither my local install or any of my dedicated servers have this folder structure.

I have no idea when. Stopped playing for a year and uninstalled it, excluding the mods, because the main game + DLCs were taking up so much space. Early this year, I was invited to play in dedi (2 different occasions - fjörður map & just vanilla), thus, had to reinstall it. 1 has minimal number of mods while the other had no mods. In either instance, loading the game took time & unsubbing to all mods sped it up.

> The dual notices delineates the portion of output directly created by the original author and is there as a mark of respect so I would prefer to leave it, you are welcome to edit the code and comment out line 210 with a // in program.cs

If it was intended, I'll leave it be. Thanks for letting me know how to do it though.

**Comment by vavavr00m** [comment]
> Can you upload this mod from your folder in a zip: 1681125667 somewhere, I can grab it and i'll see if I can fix it for this folder/file structure.

Sure. Here ya go.

URL: https://mega.nz/file/WYFEESKB
Decryption: l1w1RheGXKQEwyr5NXHzYpX1U48aSKmACDezhEGt_kg

**Comment by poynty** [comment]
Thanks, I'll give it a go, will be a separate project in the solution. Out of interest, with one of the mods you have, do you have any verified working spawn codes you could provide and for which mod? If I recall I think you have Primal Fear which would be an ideal candidate. 

Also, what is in the "\ARK\ShooterGame\Content\Mods\" folder you have? Any sign of a symbolic link to "\SteamLibrary\steamapps\workshop\content\346110\"?

EDIT: Turns out I do have a similar directory structure! I have a theory which you can help test. I think the folder you are looking in is the steam workshop cache. This would explain the compressed assets. I think if you join a server running the mod you are interested in, or start a single player game with the mod it should be copied to the Content\Mods folder. However, I could be completely wrong about this xD

**Comment by vavavr00m** [comment]
> Thanks, I'll give it a go, will be a separate project in the solution. Out of interest, with one of the mods you have, do you have any verified working spawn codes you could provide and for which mod? If I recall I think you have Primal Fear which would be an ideal candidate.

You're welcome. ArkCodeGeneratorRedux did not produce any output from any mods located in `\SteamLibrary\steamapps\workshop\content\346110`. Did you mean spawn codes generated in the `\SteamLibrary\steamapps\common\ARK\ShooterGame\Content\Mods` folder?

> Also, what is in the "\ARK\ShooterGame\Content\Mods" folder you have? 

It seems mods were copied from `\SteamLibrary\steamapps\workshop\content\346110` to `\SteamLibrary\steamapps\common\ARK\ShooterGame\Content\Mods` as well as some of the maps but I have not been able to download every map yet. 

> Any sign of a symbolic link to "\SteamLibrary\steamapps\workshop\content\346110"?

I don't think it is ([Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) is installed and it's supposed to have different overlay icons for hardlink/symlink/junction and this one folder doesn't have any) but a different directory - `\SteamLibrary\steamapps\common\ARK\Mods` - is a symbolic link to `\SteamLibrary\steamapps\workshop\content\346110`

> EDIT: Turns out I do have a similar directory structure! I have a theory which you can help test. I think the folder you are looking in is the steam workshop cache. This would explain the compressed assets. I think if you join a server running the mod you are interested in, or start a single player game with the mod it should be copied to the Content\Mods folder. However, I could be completely wrong about this xD

You are right again about the cache. I hadn't launched Ark after reinstalling mods and before this issue was raised. Writing a batch script (newbie!) to automate fetching the spawn codes from content\346110 kept me busy and I was in pain since I woke up yesterday; no energy to play and didn't think launching Ark would make a difference. Are you still going to add support for assets in `\SteamLibrary\steamapps\workshop\content\346110` now that we know the mods are being copied over? There are times when I just need to grab the codes and not launch the game. Also, it takes additional time & space to install mods too (as in from content\346110 to Content\Mods).

On a different note, do you have plans on adding support for the following?

1. Generating Simple Spawners BP - It seems it's from the Creature Spawncodes. Will it be easy to implement? If I remember it correctly, PullResourceAdditions is also just a reformat of Item Spawncodes.

2. Fetching mod's name/ID/URL/path and writing it to Output.txt

**Comment by poynty** [comment]
Ah good to see we figured it out. I can probably add 1 and 2 to the current code but to support the cache will take a re-write to do it well and if I am doing that then I may as well make it scan every mod folder and generate a file per valid mod in one pass.

I'll probably do the additions this weekend, if I do the rewrite, that will be at some point in the future.

**Comment by vavavr00m** [comment]
That's great. I'll patiently wait for the rewrite. Looking forward to seeing an update soon if you are able to add 1 & 2 this weekend. Have a good rest of your day.

**Comment by poynty** [comment]
Update with the new stuff pushed so pull the changes and rebuild. Hopefully it works xD Will close this for now, if you have problems please open a new issue.
