### ISSUE TITLE
[Feature Request] Support for folders without PrimalGameData

### ISSUE THREAD

**Issue by vavavr00m** [poynty/ArkCodeGeneratorRedux#3]
There are spawnable items and, possibly, creatures, tamed creatures and engrams without PrimalGameData. Any chance it could be supported soon or will it be included in the rewrite as well?

To name a few:

Charge Battery
Nameless Venom
Plant Species Y Seed
Plant Species Y Trap
Plant Species Z Seed
Plant Species Z Fruit
Plant Species R-1 Seed
Plant Species R-2 Seed
Plant Species R-3 Seed
Plant Species R-4 Seed
Plant Species R-5 Seed

For your reference, attached the [dir list](https://github.com/poynty/ArkCodeGeneratorRedux/files/11758671/ARK.zip) of the entire ARK folder (all DLCs included). Unsubscribing from all the mods & verifiying game files didn't remove the mods completely from ARK, thus, the ones in the mods folder were manually removed. There are probably leftovers in other folders.

**Comment by vavavr00m** [comment]
For your reference, attached the [dir list](https://github.com/poynty/ArkCodeGeneratorRedux/files/11758671/ARK.zip) of the entire ARK folder (all DLCs included). Unsubscribing from all the mods & verifiying game files didn't remove the mods entirely from ARK, thus, the ones in the mods folder were manually removed. There are probably leftovers in other folders.

**Comment by poynty** [comment]
I may support this in the new program, "Ark Gollum". Its architecture lends itself better to accomplish it.

**Comment by vavavr00m** [comment]
If you need a tester once Ark Gollum is in a usable state, just hit me up.
