### ISSUE TITLE
[Feature Request] Support for generating GFI codes

### ISSUE THREAD

**Issue by vavavr00m** [poynty/ArkCodeGeneratorRedux#4]
https://usebeacon.app/spawn/ - 2638 entries but has a list of the shortest possible GFI codes. Still missed Beer Liquid, a magenta coloring variation, some malfunctioned dinos, etc.

https://arkcheat.com/creature-ids - has more entries than usebeacon but isn't updated with the lastest creatures

- Creatures IDs - 639 entries
- Item IDs - 2156 entries

https://ark.wiki.gg/wiki/Beacon_IDs - arkcheat doesn't have them listed while usebeacon only has 4. I haven't tried spawning these so can't guarantee it will work as GFI code.

**Comment by poynty** [comment]
I presume these are non-modded items? If so any support will be in the re-write.

**Comment by vavavr00m** [comment]
Non-modded. Gotcha!

**Comment by poynty** [comment]
I have what this program does implemented in the new one already, I'm easy with how it comes to releasing it, I can either release it in its development state with potentially breaking bugs and do feature updates or I can wait till its basically feature complete.

**Comment by vavavr00m** [comment]
Whatever works for you. I don't mind testing a potentially buggy experimental version. After all, I downloaded the entire Ark just to check if redux will work in vanilla.

**Comment by poynty** [comment]
Here is the new repo <https://github.com/poynty/ArkGollum>
